title: Yuan Zhang - personal blog
email: mike.zy7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/mikezhang95.github.io" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Yuan Zhang
author-pic: face.jpg
about-author: My name is Yuan Zhang. I am currently enrolled in MSc Machine Learning at University College London. Prior to that, I obtained a BSc Engineering degree at Tsinghua University, China.


# Contact links
email: mike.zy7@gmail.com
phone: +8615210325091
website: https://mikezhang95.github.io
linkedin:
github: mikezhang95
facebook: https://www.facebook.com/mike.beckham.794 # Add your Facebook handle
twitter: # Add your Twitter handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
#mailchimp: # Add your MailChimp form identifier.

# Disqus
#discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: UA-120513439-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
